version: "3"
services:
  access_management:
    container_name: access_management
    build:
      context: .
      args:
        - APP=access_management
    restart: always
    ports:
      - 3000:3000

  billing:
    container_name: billing
    build:
      context: .
      args:
        - APP=billing
    restart: always
    ports:
      - 3001:3001

  service_management:
    container_name: service_management
    build:
      context: .
      args:
        - APP=service_management
    restart: always
    ports:
      - 3003:3003

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
