version: "3"
services:
  access_management:
    container_name: access_management
    build:
      context: .
      args:
        - APP=access_management
    restart: always
    ports:
      - 3000:3000
  billing:
    container_name: billing
    build:
      context: .
      args:
        - APP=billing
    restart: always
    ports:
      - 3001:3001
  notifications:
    container_name: notifications
    build:
      context: .
      args:
        - APP=notifications
    restart: always
    ports:
      - 3002:3002
  service_management:
    container_name: service_management
    build:
      context: .
      args:
        - APP=service_management
    restart: always
    ports:
      - 3003:3003